version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: secondaVita
        MYSQL_USER: secondaVita
        MYSQL_PASSWORD: secondaVita
    ports:
        - "3306:3306"

volumes:
  data:
#ignore for now : not functionnal